### ISSUE TITLE
Questions on sorting with accents

### ISSUE THREAD

**Issue by motss** [sindresorhus/alpha-sort#4] opened 2017-04-04 07:06 UTC
Isn't this ['a'.localeCompare('å') === -1](https://github.com/sindresorhus/alpha-sort/blob/master/index.js#L6) always be true and we ended up using the fallback always?

**Comment by sindresorhus** [comment] 2017-04-05 04:26
It was added back in https://github.com/sindresorhus/alpha-sort/commit/a1bc075c40749774fbbc9e63c72e1a6ec75327d0. On Node.js v0.10 it had the following result:

```js
'a'.localeCompare('å')
//=> -132
```

The check is indeed broken now, but the implementation is also broken:

```js
'b'.localeCompare('å')
//=> 1
```

So the check being broken haven't actually caused any problems.

**Comment by sindresorhus** [comment] 2017-04-05 04:27
I've pushed a fix in case Node.js is fixed in the future (The issue is still there in Node.js 7.8.0 though).

Can you look https://github.com/sindresorhus/alpha-sort/commit/9b1652a3f3561a30e6e75e54d9e4e4c54753e2ef over and 👍 ?

**Closed as completed** 2017-04-05 04:27 UTC

**Comment by motss** [comment] 2017-04-05 07:24
@sindresorhus 

Could you please clarify why `'b'.localeCompare('å')` should be less than 1? I don't quite understand this?

**Comment by sindresorhus** [comment] 2017-04-05 07:57
> A negative number if the reference string occurs before the compare string; - https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

That means it should return `-1` since `b` should come before `å`, but it returns `1`, so it will sort `å` before `b`, which is clearly wrong.

Try commenting out the https://github.com/sindresorhus/alpha-sort/blob/1d47b91a2aba6fc846a203920ca4e7183258d308/index.js#L6-L9 part and you'll see the test failing.

**Comment by motss** [comment] 2017-04-05 09:20
@sindresorhus Correct me if I'm wrong.

Should it compare based on the character reference code?

Like the following:

```js
'a'.charCodeAt(); // 97
'b'.charCodeAt(); // 98
'å'.charCodeAt(); // 229

['b', 'a', 'å'].sort(Intl.Collator().compare);
// gives ['a', 'å', 'b'] but should be ['a', 'b', 'å']
```

**Comment by sindresorhus** [comment] 2017-04-05 09:33
@motss No, it should compare based on Unicode sorting, but that's broken in Node.js. That's why we fall back to character code, which at least isn't entirely incorrect.

**Comment by motss** [comment] 2017-04-05 13:22
@sindresorhus Ok. Now I know the sorting should be based on the Unicode of the character. Then is it advisable to convert a character into Unicode (I've found certain ways to do the conversion) then do the comparison?

**Comment by sindresorhus** [comment] 2017-04-05 13:34
I'm not really interested in taking the fix further. This workaround works for my use-cases. It should really be fixed in Node.js. Use your energy getting that done instead.

**Comment by motss** [comment] 2017-04-05 13:56
OK. Thank you so much for the explanation.
